PROGRAMS = GeoConvert TransverseMercatorTest CartConvert Geod EquidistantTest \
	GeoidEval

VSPROJECTS = $(addsuffix .vcproj,$(PROGRAMS))

all:
	@:
install:
	@:
clean:
	@:
list:
	@echo $(VSPROJECTS)

.PHONY: all install list clean
