GeographicLib: GeographicLib::GravityModel Class Reference
GeographicLib::GravityModel Class Reference
Model of the earth's gravity field.
#include <GeographicLib/GravityModel.hpp>
Public Types
enum mask {
NONE, GRAVITY, DISTURBANCE, DISTURBING_POTENTIAL,
SPHERICAL_ANOMALY, GEOID_HEIGHT, ALL
}
Public Member Functions
Setting up the gravity model
GravityModel (const std::string &name, const std::string &path="")
Compute gravity in geodetic coordinates
Math::real Gravity (real lat, real lon, real h, real &gx, real &gy, real &gz) const throw ()
Math::real Disturbance (real lat, real lon, real h, real &deltax, real &deltay, real &deltaz) const throw ()
Math::real GeoidHeight (real lat, real lon) const throw ()
void SphericalAnomaly (real lat, real lon, real h, real &Dg01, real &xi, real &eta) const throw ()
Compute gravity in geocentric coordinates
Math::real W (real X, real Y, real Z, real &gX, real &gY, real &gZ) const throw ()
Math::real V (real X, real Y, real Z, real &GX, real &GY, real &GZ) const throw ()
Math::real T (real X, real Y, real Z, real &deltaX, real &deltaY, real &deltaZ) const throw ()
Math::real T (real X, real Y, real Z) const throw ()
Math::real U (real X, real Y, real Z, real &gammaX, real &gammaY, real &gammaZ) const throw ()
Math::real Phi (real X, real Y, real &fX, real &fY) const throw ()
Compute gravity on a circle of constant latitude
GravityCircle Circle (real lat, real h, unsigned caps=ALL) const
Inspector functions
const NormalGravity & ReferenceEllipsoid () const throw ()
const std::string & Description () const throw ()
const std::string & DateTime () const throw ()
const std::string & GravityFile () const throw ()
const std::string & GravityModelName () const throw ()
const std::string & GravityModelDirectory () const throw ()
Math::real MajorRadius () const throw ()
Math::real MassConstant () const throw ()
Math::real ReferenceMassConstant () const throw ()
Math::real AngularVelocity () const throw ()
Math::real Flattening () const throw ()
Static Public Member Functions
static std::string DefaultGravityPath ()
static std::string DefaultGravityName ()
Friends
class GravityCircle
Detailed Description
Model of the earth's gravity field.
Evaluate the earth's gravity field according to a model. The supported models treat only the gravitational field exterior to the mass of the earth. When computing the field at points near (but above) the surface of the earth a small correction can be applied to account for the mass of the atomsphere above the point in question; see The effect of the mass of the atmosphere. Determining the geoid height entails correcting for the mass of the earth above the geoid. The egm96 and egm2008 include separate correction terms to account for this mass.
Definitions and terminology (from Heiskanen and Moritz, Sec 2-13):
V = gravitational potential;
Phi = rotational potential;
W = V + Phi = T + U = total potential;
V0 = normal gravitation potential;
U = V0 + Phi = total normal potential;
T = W - U = V - V0 = anomalous or disturbing potential;
g = grad W = gamma + delta;
f = grad Phi;
Gamma = grad V0;
gamma = grad U;
delta = grad T = gravity disturbance vector = gP - gammaP;
delta g = gravity disturbance = gP - gammaP;
Delta g = gravity anomaly vector = gP - gammaQ; here the line PQ is perpendicular to ellipsoid and the potential at P equals the normal potential at Q;
Delta g = gravity anomaly = gP - gammaQ;
(xi, eta) deflection of the vertical, the difference in directions of gP and gammaQ, xi = NS, eta = EW.
X, Y, Z, geocentric coordinates;
x, y, z, local cartesian coordinates used to denote the east, north and up directions.
See Gravity models for details of how to install the gravity model and the data format.
References:
W. A. Heiskanen and H. Moritz, Physical Geodesy (Freeman, San Francisco, 1967).
Example of use:
// Example of using the GeographicLib::GravityModel class
// $Id: fde4f431ed9c43e9e0ec797e302f32a373cdd219 $
#include <iostream>
#include <exception>
#include <GeographicLib/GravityModel.hpp>
using namespace std;
using namespace GeographicLib;
int main() {
  try {
    GravityModel grav("egm96");
    double lat = 27.99, lon = 86.93, h = 8820; // Mt Everest
    double gx, gy, gz;
    grav.Gravity(lat,lon, h, gx, gy, gz);
    cout << gx << " " << gy << " " << gz << "\n";
  }
  catch (const exception& e) {
    cerr << "Caught exception: " << e.what() << "\n";
    return 1;
  }
  return 0;
}
Gravity is a command-line utility providing access to the functionality of GravityModel and GravityCircle.
Member Enumeration Documentation
enum GeographicLib::GravityModel::mask
Bit masks for the capabilities to be given to the GravityCircle object produced by Circle.
Enumerator:
NONE
No capabilities.
GRAVITY
Allow calls to GravityCircle::Gravity, GravityCircle::W, and GravityCircle::V.
DISTURBANCE
Allow calls to GravityCircle::Disturbance and GravityCircle::T.
DISTURBING_POTENTIAL
Allow calls to GravityCircle::T(real lon) (i.e., computing the disturbing potential and not the gravity disturbance vector).
SPHERICAL_ANOMALY
Allow calls to GravityCircle::SphericalAnomaly.
GEOID_HEIGHT
Allow calls to GravityCircle::GeoidHeight.
ALL
All capabilities.
Definition at line 122 of file GravityModel.hpp.
Constructor & Destructor Documentation
GeographicLib::GravityModel::GravityModel (const std::string & name, const std::string & path = "") [explicit]
Construct a gravity model.
Parameters:
[in] name the name of the model.
[in] path (optional) directory for data file.
A filename is formed by appending ".egm" (World Gravity Model) to the name. If path is specified (and is non-empty), then the file is loaded from directory, path. Otherwise the path is given by DefaultGravityPath(). This may throw an exception because the file does not exist, is unreadable, or is corrupt.
This file contains the metadata which specifies the properties of the model. The coefficients for the spherical harmonic sums are obtained from a file obtained by appending ".cof" to metadata file (so the filename ends in ".egm.cof").
Definition at line 43 of file GravityModel.cpp.
References DefaultGravityPath(), GeographicLib::SphericalEngine::coeff::readcoeffs(), GeographicLib::SphericalHarmonic::Coefficients(), GeographicLib::SphericalEngine::coeff::nmx(), GeographicLib::Math::sq(), GeographicLib::NormalGravity::MassConstant(), GeographicLib::SphericalEngine::coeff::N(), and GeographicLib::SphericalEngine::coeff::mmx().
Member Function Documentation
Math::real GeographicLib::GravityModel::Gravity (real lat, real lon, real h, real & gx, real & gy, real & gz) const throw ()
Evaluate the gravity at an arbitrary point above (or below) the ellipsoid.
Parameters:
[in] lat the geographic latitude (degrees).
[in] lon the geographic longitude (degrees).
[in] h the height above the ellipsoid (meters).
[out] gx the easterly component of the acceleration (m s-2).
[out] gy the northerly component of the acceleration (m s-2).
[out] gz the upward component of the acceleration (m s-2); this is usually negative.
Returns:
W the sum of the gravitational and centrifugal potentials.
The function includes the effects of the earth's rotation.
Definition at line 291 of file GravityModel.cpp.
Referenced by main().
Math::real GeographicLib::GravityModel::Disturbance (real lat, real lon, real h, real & deltax, real & deltay, real & deltaz) const throw ()
Evaluate the gravity disturbance vector at an arbitrary point above (or below) the ellipsoid.
Parameters:
[in] lat the geographic latitude (degrees).
[in] lon the geographic longitude (degrees).
[in] h the height above the ellipsoid (meters).
[out] deltax the easterly component of the disturbance vector (m s-2).
[out] deltay the northerly component of the disturbance vector (m s-2).
[out] deltaz the upward component of the disturbance vector (m s-2).
Returns:
T the corresponding disturbing potential.
Definition at line 299 of file GravityModel.cpp.
Referenced by main().
Math::real GeographicLib::GravityModel::GeoidHeight (real lat, real lon) const throw ()
Evaluate the geoid height.
Parameters:
[in] lat the geographic latitude (degrees).
[in] lon the geographic longitude (degrees).
Returns:
N the height of the geoid above the ReferenceEllipsoid() (meters).
This calls NormalGravity::U for ReferenceEllipsoid(). Some approximations are made in computing the geoid height so that the results of the NGA codes are reproduced accurately. Details are given in Details of the geoid height and anomaly calculations.
Definition at line 277 of file GravityModel.cpp.
References GeographicLib::Math::hypot().
Referenced by main().
void GeographicLib::GravityModel::SphericalAnomaly (real lat, real lon, real h, real & Dg01, real & xi, real & eta) const throw ()
Evaluate the components of the gravity anomaly vector using the spherical approximation.
Parameters:
[in] lat the geographic latitude (degrees).
[in] lon the geographic longitude (degrees).
[in] h the height above the ellipsoid (meters).
[out] Dg01 the gravity anomaly (m s-2).
[out] xi the northerly component of the deflection of the vertical (degrees).
[out] eta the easterly component of the deflection of the vertical (degrees).
The spherical approximation (see Heiskanen and Moritz, Sec 2-14) is used so that the results of the NGA codes are reproduced accurately. approximations used here. Details are given in Details of the geoid height and anomaly calculations.
Definition at line 250 of file GravityModel.cpp.
References GeographicLib::Math::hypot().
Referenced by main().
Math::real GeographicLib::GravityModel::W (real X, real Y, real Z, real & gX, real & gY, real & gZ) const throw ()
Evaluate the components of the acceleration due to gravity and the centrifugal acceleration in geocentric coordinates.
Parameters:
[in] X geocentric coordinate of point (meters).
[in] Y geocentric coordinate of point (meters).
[in] Z geocentric coordinate of point (meters).
[out] gX the X component of the acceleration (m s-2).
[out] gY the Y component of the acceleration (m s-2).
[out] gZ the Z component of the acceleration (m s-2).
Returns:
W = V + Phi the sum of the gravitational and centrifugal potentials (m2 s-2).
This calls NormalGravity::U for ReferenceEllipsoid().
Definition at line 241 of file GravityModel.cpp.
Math::real GeographicLib::GravityModel::V (real X, real Y, real Z, real & GX, real & GY, real & GZ) const throw ()
Evaluate the components of the acceleration due to gravity in geocentric coordinates.
Parameters:
[in] X geocentric coordinate of point (meters).
[in] Y geocentric coordinate of point (meters).
[in] Z geocentric coordinate of point (meters).
[out] GX the X component of the acceleration (m s-2).
[out] GY the Y component of the acceleration (m s-2).
[out] GZ the Z component of the acceleration (m s-2).
Returns:
V = W - Phi the gravitational potential (m2 s-2).
Definition at line 229 of file GravityModel.cpp.
Math::real GeographicLib::GravityModel::T (real X, real Y, real Z, real & deltaX, real & deltaY, real & deltaZ) const throw () [inline]
Evaluate the components of the gravity disturbance in geocentric coordinates.
Parameters:
[in] X geocentric coordinate of point (meters).
[in] Y geocentric coordinate of point (meters).
[in] Z geocentric coordinate of point (meters).
[out] deltaX the X component of the gravity disturbance (m s-2).
[out] deltaY the Y component of the gravity disturbance (m s-2).
[out] deltaZ the Z component of the gravity disturbance (m s-2).
Returns:
T = W - U the disturbing potential (also called the anomalous potential) (m2 s-2).
Definition at line 322 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::T (real X, real Y, real Z) const throw () [inline]
Evaluate disturbing potential in geocentric coordinates.
Parameters:
[in] X geocentric coordinate of point (meters).
[in] Y geocentric coordinate of point (meters).
[in] Z geocentric coordinate of point (meters).
Returns:
T = W - U the disturbing potential (also called the anomalous potential) (m2 s-2).
Definition at line 335 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::U (real X, real Y, real Z, real & gammaX, real & gammaY, real & gammaZ) const throw () [inline]
Evaluate the components of the acceleration due to normal gravity and the centrifugal acceleration in geocentric coordinates.
Parameters:
[in] X geocentric coordinate of point (meters).
[in] Y geocentric coordinate of point (meters).
[in] Z geocentric coordinate of point (meters).
[out] gammaX the X component of the normal acceleration (m s-2).
[out] gammaY the Y component of the normal acceleration (m s-2).
[out] gammaZ the Z component of the normal acceleration (m s-2).
Returns:
U = V0 + Phi the sum of the normal gravitational and centrifugal potentials (m2 s-2).
This calls NormalGravity::U for ReferenceEllipsoid().
Definition at line 359 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::Phi (real X, real Y, real & fX, real & fY) const throw () [inline]
Evaluate the centrifugal acceleration in geocentric coordinates.
Parameters:
[in] X geocentric coordinate of point (meters).
[in] Y geocentric coordinate of point (meters).
[out] fX the X component of the centrifugal acceleration (m s-2).
[out] fY the Y component of the centrifugal acceleration (m s-2).
Returns:
Phi the centrifugal potential (m2 s-2).
This calls NormalGravity::Phi for ReferenceEllipsoid().
Definition at line 376 of file GravityModel.hpp.
GravityCircle GeographicLib::GravityModel::Circle (real lat, real h, unsigned caps = ALL) const
Create a GravityCircle object to allow the gravity field at many points with constant lat and h and varying lon to be computed efficiently.
Parameters:
[in] lat latitude of the point (degrees).
[in] h the height of the point above the ellipsoid (meters).
[in] caps bitor'ed combination of GravityModel::mask values specifying the capabilities of the resulting GravityCircle object.
Returns:
a GravityCircle object whose member functions computes the gravitational field at a particular values of lon.
The GravityModel::mask values are
caps |= GravityModel::GRAVITY
caps |= GravityModel::DISTURBANCE
caps |= GravityModel::DISTURBING_POTENTIAL
caps |= GravityModel::SPHERICAL_ANOMALY
caps |= GravityModel::GEOID_HEIGHT
The default value of caps is GravityModel::ALL which turns on all the capabilities. If an unsupported function is invoked, it will return NaNs. Note that GravityModel::GEOID_HEIGHT will only be honored if h = 0.
If the field at several points on a circle of latitude need to be calculated then creating a GravityCircle object and using its member functions will be substantially faster, especially for high-degree models. See Geoid heights on a multi-processor system for an example of using GravityCircle (together with OpenMP) to speed up the computation of geoid heights.
Definition at line 309 of file GravityModel.cpp.
References GeographicLib::NormalGravity::Earth(), GeographicLib::Math::hypot(), GeographicLib::NormalGravity::SurfaceGravity(), GeographicLib::NormalGravity::U(), GeographicLib::NormalGravity::Phi(), GravityCircle, GeographicLib::SphericalHarmonic::Circle(), and GeographicLib::SphericalHarmonic1::Circle().
Referenced by main().
const NormalGravity& GeographicLib::GravityModel::ReferenceEllipsoid () const throw () [inline]
Returns:
the NormalGravity object for the reference ellipsoid.
Definition at line 423 of file GravityModel.hpp.
const std::string& GeographicLib::GravityModel::Description () const throw () [inline]
Returns:
the description of the gravity model, if available, in the data file; if absent, return "NONE".
Definition at line 429 of file GravityModel.hpp.
Referenced by main().
const std::string& GeographicLib::GravityModel::DateTime () const throw () [inline]
Returns:
date of the model; if absent, return "UNKNOWN".
Definition at line 434 of file GravityModel.hpp.
Referenced by main().
const std::string& GeographicLib::GravityModel::GravityFile () const throw () [inline]
Returns:
full file name used to load the gravity model.
Definition at line 439 of file GravityModel.hpp.
Referenced by main().
const std::string& GeographicLib::GravityModel::GravityModelName () const throw () [inline]
Returns:
"name" used to load the gravity model (from the first argument of the constructor, but this may be overridden by the model file).
Definition at line 445 of file GravityModel.hpp.
Referenced by main().
const std::string& GeographicLib::GravityModel::GravityModelDirectory () const throw () [inline]
Returns:
directory used to load the gravity model.
Definition at line 450 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::MajorRadius () const throw () [inline]
Returns:
a the equatorial radius of the ellipsoid (meters).
Definition at line 455 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::MassConstant () const throw () [inline]
Returns:
GM the mass constant of the model (m3 s-2); this is the product of G the gravitational constant and M the mass of the earth (usually including the mass of the earth's atmosphere).
Definition at line 463 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::ReferenceMassConstant () const throw () [inline]
Returns:
GM the mass constant of the ReferenceEllipsoid() (m3 s-2).
Definition at line 469 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::AngularVelocity () const throw () [inline]
Returns:
omega the angular velocity of the model and the ReferenceEllipsoid() (rad s-1).
Definition at line 476 of file GravityModel.hpp.
Math::real GeographicLib::GravityModel::Flattening () const throw () [inline]
Returns:
f the flattening of the ellipsoid.
Definition at line 482 of file GravityModel.hpp.
std::string GeographicLib::GravityModel::DefaultGravityPath () [static]
Returns:
the default path for gravity model data files.
This is the value of the environment variable GRAVITY_PATH, if set; otherwise, it is $GEOGRAPHICLIB_DATA/gravity if the environment variable GEOGRAPHICLIB_DATA is set; otherwise, it is a compile-time default (/usr/local/share/GeographicLib/gravity on non-Windows systems and C:/Documents and Settings/All Users/Application Data/GeographicLib/gravity on Windows systems).
Definition at line 343 of file GravityModel.cpp.
References GEOGRAPHICLIB_DATA.
Referenced by main(), and GravityModel().
std::string GeographicLib::GravityModel::DefaultGravityName () [static]
Returns:
the default name for the gravity model.
This is the value of the environment variable GRAVITY_NAME, if set, otherwise, it is "egm96". The GravityModel class does not use this function; it is just provided as a convenience for a calling program when constructing a GravityModel object.
Definition at line 356 of file GravityModel.cpp.
References GRAVITY_DEFAULT_NAME.
Referenced by main().
Friends And Related Function Documentation
friend class GravityCircle [friend]
Definition at line 90 of file GravityModel.hpp.
Referenced by Circle().
The documentation for this class was generated from the following files:
GravityModel.hpp
GravityModel.cpp