GeographicLib: GeographicLib::Ellipsoid Class Reference
GeographicLib::Ellipsoid Class Reference
Properties of an ellipsoid.
#include <GeographicLib/Ellipsoid.hpp>
Public Member Functions
Constructor
Ellipsoid (real a, real f)
Ellipsoid dimensions.
Math::real MajorRadius () const throw ()
Math::real MinorRadius () const throw ()
Math::real QuarterMeridian () const throw ()
Math::real Area () const throw ()
Math::real Volume () const throw ()
Ellipsoid shape
Math::real Flattening ()
Math::real SecondFlattening ()
Math::real ThirdFlattening ()
Math::real EccentricitySq ()
Math::real SecondEccentricitySq ()
Math::real ThirdEccentricitySq ()
Latitude conversion.
Math::real ParametricLatitude (real phi) const throw ()
Math::real InverseParametricLatitude (real beta) const throw ()
Math::real GeocentricLatitude (real phi) const throw ()
Math::real InverseGeocentricLatitude (real theta) const throw ()
Math::real RectifyingLatitude (real phi) const throw ()
Math::real InverseRectifyingLatitude (real mu) const throw ()
Math::real AuthalicLatitude (real phi) const throw ()
Math::real InverseAuthalicLatitude (real xi) const throw ()
Math::real ConformalLatitude (real phi) const throw ()
Math::real InverseConformalLatitude (real chi) const throw ()
Math::real IsometricLatitude (real phi) const throw ()
Math::real InverseIsometricLatitude (real psi) const throw ()
Other quantities.
Math::real CircleRadius (real phi) const throw ()
Math::real CircleHeight (real phi) const throw ()
Math::real MeridianDistance (real phi) const throw ()
Math::real MeridionalCurvatureRadius (real phi) const throw ()
Math::real TransverseCurvatureRadius (real phi) const throw ()
Static Public Member Functions
Eccentricity conversions.
static Math::real SecondFlatteningToFlattening (real fp) throw ()
static Math::real FlatteningToSecondFlattening (real f) throw ()
static Math::real ThirdFlatteningToFlattening (real n) throw ()
static Math::real FlatteningToThirdFlattening (real f) throw ()
static Math::real EccentricitySqToFlattening (real e2) throw ()
static Math::real FlatteningToEccentricitySq (real f) throw ()
static Math::real SecondEccentricitySqToFlattening (real ep2) throw ()
static Math::real FlatteningToSecondEccentricitySq (real f) throw ()
static Math::real ThirdEccentricitySqToFlattening (real epp2) throw ()
static Math::real FlatteningToThirdEccentricitySq (real f) throw ()
Static Public Attributes
static const Ellipsoid WGS84
Detailed Description
Properties of an ellipsoid.
This class returns various properties of the ellipsoid and converts between various types of latitudes. The latitude conversions are also possible using the various projections supported by GeographicLib; but Ellipsoid provides more direct access (sometimes using private functions of the projection classes). Ellipsoid::RectifyingLatitude, Ellipsoid::InverseRectifyingLatitude, and Ellipsoid::MeridianDistance provide functionality which can be provided by the Geodesic class. However Geodesic uses a series approximation (valid for abs f < 1/150), whereas Ellipsoid computes these quantities using EllipticFunction which provides accurate results even when f is large. Use of this class should be limited to -3 < f < 3/4 (i.e., 1/4 < b/a < 4).
Example of use:
// Example of using the GeographicLib::Ellipsoid class
// $Id: dd3a570b1a112463405e4020eabe32f84672efde $
#include <iostream>
#include <exception>
#include <GeographicLib/Ellipsoid.hpp>
using namespace std;
using namespace GeographicLib;
int main() {
  try {
    Ellipsoid wgs84(Constants::WGS84_a(), Constants::WGS84_f());
    // Alternatively: const Ellipsoid& wgs84 = Ellipsoid::WGS84;
    cout << "The latitude half way between the equator and the pole is "
         << wgs84.InverseRectifyingLatitude(45) << "\n";
    cout << "Half the area of the ellipsoid lies between latitudes +/- "
         << wgs84.InverseAuthalicLatitude(30) << "\n";
    cout << "The northernmost edge of a square Mercator map at latitude "
         << wgs84.InverseIsometricLatitude(180) << "\n";
  }
  catch (const exception& e) {
    cerr << "Caught exception: " << e.what() << "\n";
    return 1;
  }
  return 0;
}
Definition at line 41 of file Ellipsoid.hpp.
Constructor & Destructor Documentation
GeographicLib::Ellipsoid::Ellipsoid (real a, real f)
Constructor for a ellipsoid with
Parameters:
[in] a equatorial radius (meters).
[in] f flattening of ellipsoid. Setting f = 0 gives a sphere. Negative f gives a prolate ellipsoid. If f > 1, set flattening to 1/f.
An exception is thrown if either of the axes of the ellipsoid is non-positive.
Definition at line 22 of file Ellipsoid.cpp.
Member Function Documentation
Math::real GeographicLib::Ellipsoid::MajorRadius () const throw () [inline]
Returns:
a the equatorial radius of the ellipsoid (meters). This is the value used in the constructor.
Definition at line 87 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::MinorRadius () const throw () [inline]
Returns:
b the polar semi-axis (meters).
Definition at line 92 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::QuarterMeridian () const throw ()
Returns:
L the distance between the equator and a pole along a meridian (meters). For a sphere L = (pi / 2) a. The radius of a sphere with the same meridian length is L / (pi / 2).
Definition at line 40 of file Ellipsoid.cpp.
References GeographicLib::EllipticFunction::E().
Math::real GeographicLib::Ellipsoid::Area () const throw ()
Returns:
A the total area of the ellipsoid (meters2). For a sphere A = 4pi a2. The radius of a sphere with the same area is sqrt(A / (4 pi)).
Definition at line 43 of file Ellipsoid.cpp.
References GeographicLib::Math::atanh(), and GeographicLib::Math::sq().
Math::real GeographicLib::Ellipsoid::Volume () const throw () [inline]
Returns:
V the total volume of the ellipsoid (meters3). For a sphere V = (4pi / 3) a3. The radius of a sphere with the same volume is cbrt(V / (4 pi / 3)).
Definition at line 113 of file Ellipsoid.hpp.
References GeographicLib::Math::sq().
Math::real GeographicLib::Ellipsoid::Flattening () [inline]
Returns:
f = (a - b) / a, the flattening of the ellipsoid. This is the value used in the constructor. This is zero, positive, or negative for a sphere, oblate ellipsoid, or prolate ellipsoid.
Definition at line 126 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::SecondFlattening () [inline]
Returns:
f ' = (a - b) / b, the second flattening of the ellipsoid. This is zero, positive, or negative for a sphere, oblate ellipsoid, or prolate ellipsoid.
Definition at line 133 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::ThirdFlattening () [inline]
Returns:
n = (a - b) / (a + b), the third flattening of the ellipsoid. This is zero, positive, or negative for a sphere, oblate ellipsoid, or prolate ellipsoid.
Definition at line 140 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::EccentricitySq () [inline]
Returns:
e2 = (a2 - b2) / a2, the eccentricity squared of the the ellipsoid. This is zero, positive, or negative for a sphere, oblate ellipsoid, or prolate ellipsoid.
Definition at line 148 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::SecondEccentricitySq () [inline]
Returns:
e' 2 = (a2 - b2) / b2, the second eccentricity squared of the the ellipsoid. This is zero, positive, or negative for a sphere, oblate ellipsoid, or prolate ellipsoid.
Definition at line 156 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::ThirdEccentricitySq () [inline]
Returns:
e'' 2 = (a2 - b2) / (a2 + b2), the third eccentricity squared of the the ellipsoid. This is zero, positive, or negative for a sphere, oblate ellipsoid, or prolate ellipsoid.
Definition at line 165 of file Ellipsoid.hpp.
Math::real GeographicLib::Ellipsoid::ParametricLatitude (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
beta the parametric latitude (degrees).
The geographic latitude, phi, is the angle beween the equatorial plane and a vector normal to the surface of the ellipsoid.
The parametric latitude (also called the reduced latitude), beta, allows the cartesian coordinated of a meridian to be expressed conveniently in parametric form as
R = a cos beta
Z = b sin beta
where a and b are the equatorial radius and the polar semi-axis. For a sphere beta = phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value beta lies in [-90o, 90o].
Definition at line 51 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::InverseParametricLatitude (real beta) const throw ()
Parameters:
[in] beta the parametric latitude (degrees).
Returns:
phi the geographic latitude (degrees).
beta must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value phi lies in [-90o, 90o].
Definition at line 54 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::GeocentricLatitude (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
theta the geocentric latitude (degrees).
The geocentric latitude, theta, is the angle beween the equatorial plane and a line between the center of the ellipsoid and a point on the ellipsoid. For a sphere theta = phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value theta lies in [-90o, 90o].
Definition at line 57 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::InverseGeocentricLatitude (real theta) const throw ()
Parameters:
[in] theta the geocentric latitude (degrees).
Returns:
phi the geographic latitude (degrees).
theta must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value phi lies in [-90o, 90o].
Definition at line 60 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::RectifyingLatitude (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
mu the rectifying latitude (degrees).
The rectifying latitude, mu, has the property that the distance along a meridian of the ellipsoid between two points with rectifying latitudes mu1 and mu2 is equal to (mu2 - mu1) L / 90o, where L = QuarterMeridian(). For a sphere mu = phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value mu lies in [-90o, 90o].
Definition at line 63 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::InverseRectifyingLatitude (real mu) const throw ()
Parameters:
[in] mu the rectifying latitude (degrees).
Returns:
phi the geographic latitude (degrees).
mu must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value phi lies in [-90o, 90o].
Definition at line 68 of file Ellipsoid.cpp.
References GeographicLib::Math::sq().
Math::real GeographicLib::Ellipsoid::AuthalicLatitude (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
xi the authalic latitude (degrees).
The authalic latitude, xi, has the property that the area of the ellipsoid between two circles with authalic latitudes xi1 and xi2 is equal to (sin xi2 - sin xi1) A / 2, where A = Area(). For a sphere xi = phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value xi lies in [-90o, 90o].
Definition at line 88 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::InverseAuthalicLatitude (real xi) const throw ()
Parameters:
[in] xi the authalic latitude (degrees).
Returns:
phi the geographic latitude (degrees).
xi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value phi lies in [-90o, 90o].
Definition at line 91 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::ConformalLatitude (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
chi the conformal latitude (degrees).
The conformal latitude, chi, gives the mapping of the ellipsoid to a sphere which which is conformal (angles are preserved) and in which the equator of the ellipsoid maps to the equator of the sphere. For a sphere chi = phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value chi lies in [-90o, 90o].
Definition at line 94 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::InverseConformalLatitude (real chi) const throw ()
Parameters:
[in] chi the conformal latitude (degrees).
Returns:
phi the geographic latitude (degrees).
chi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold. The returned value phi lies in [-90o, 90o].
Definition at line 97 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::IsometricLatitude (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
psi the isometric latitude (degrees).
The isometric latitude gives the mapping of the ellipsoid to a plane which which is conformal (angles are preserved) and in which the equator of the ellipsoid maps to a straight line of constant scale; this mapping defines the Mercator projection. For a sphere psi = sinh-1 tan phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold.
Definition at line 100 of file Ellipsoid.cpp.
References GeographicLib::Math::asinh().
Math::real GeographicLib::Ellipsoid::InverseIsometricLatitude (real psi) const throw ()
Parameters:
[in] psi the isometric latitude (degrees).
Returns:
phi the geographic latitude (degrees).
The returned value phi lies in [-90o, 90o].
Definition at line 103 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::CircleRadius (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
R = a cos beta the radius of a circle of latitude phi (meters). R (pi / 180o) gives meters per degree longitude measured along a circle of latitude.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold.
Definition at line 106 of file Ellipsoid.cpp.
References GeographicLib::Math::hypot().
Math::real GeographicLib::Ellipsoid::CircleHeight (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
Z = b sin beta the distance of a circle of latitude phi from the equator measured parallel to the ellipsoid axis (meters).
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold.
Definition at line 112 of file Ellipsoid.cpp.
References GeographicLib::Math::hypot().
Math::real GeographicLib::Ellipsoid::MeridianDistance (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
s the distance along a meridian between the equator and a point of latitude phi (meters). s is given by s = mu L / 90o, where L = QuarterMeridian()).
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold.
Definition at line 118 of file Ellipsoid.cpp.
Math::real GeographicLib::Ellipsoid::MeridionalCurvatureRadius (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
rho the meridional radius of curvature of the ellipsoid at latitude phi (meters); this is the curvature of the meridian. rho is given by rho = (180o / pi) ds / dphi, where s = MeridianDistance(); thus rho (pi / 180o) gives meters per degree latitude measured along a meridian.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold.
Definition at line 121 of file Ellipsoid.cpp.
References GeographicLib::Math::sq().
Math::real GeographicLib::Ellipsoid::TransverseCurvatureRadius (real phi) const throw ()
Parameters:
[in] phi the geographic latitude (degrees).
Returns:
nu the transverse radius of curvature of the ellipsoid at latitude phi (meters); this is the curvature of a curve on the ellipsoid which also lies in a plane perpendicular to the ellipsoid and to the meridian. nu is related to R = CircleRadius() by R = nu cos phi.
phi must lie in the range [-90o, 90o]; the result is undefined if this condition does not hold.
Definition at line 126 of file Ellipsoid.cpp.
References GeographicLib::Math::sq().
static Math::real GeographicLib::Ellipsoid::SecondFlatteningToFlattening (real fp) throw () [inline, static]
Parameters:
[in] fp = f ' = (a - b) / b, the second flattening.
Returns:
f = (a - b) / a, the flattening.
f ' should lie in (-1, inf). The returned value f lies in (-inf, 1).
Definition at line 404 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::FlatteningToSecondFlattening (real f) throw () [inline, static]
Parameters:
[in] f = (a - b) / a, the flattening.
Returns:
f ' = (a - b) / b, the second flattening.
f should lie in (-inf, 1). The returned value f ' lies in (-1, inf).
Definition at line 414 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::ThirdFlatteningToFlattening (real n) throw () [inline, static]
Parameters:
[in] n = (a - b) / (a + b), the third flattening.
Returns:
f = (a - b) / a, the flattening.
n should lie in (-1, 1). The returned value f lies in (-inf, 1).
Definition at line 424 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::FlatteningToThirdFlattening (real f) throw () [inline, static]
Parameters:
[in] f = (a - b) / a, the flattening.
Returns:
n = (a - b) / (a + b), the third flattening.
f should lie in (-inf, 1). The returned value n lies in (-1, 1).
Definition at line 434 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::EccentricitySqToFlattening (real e2) throw () [inline, static]
Parameters:
[in] e2 = e2 = (a2 - b2) / a2, the eccentricity squared.
Returns:
f = (a - b) / a, the flattening.
e2 should lie in (-inf, 1). The returned value f lies in (-inf, 1).
Definition at line 446 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::FlatteningToEccentricitySq (real f) throw () [inline, static]
Parameters:
[in] f = (a - b) / a, the flattening.
Returns:
e2 = (a2 - b2) / a2, the eccentricity squared.
f should lie in (-inf, 1). The returned value e2 lies in (-inf, 1).
Definition at line 458 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::SecondEccentricitySqToFlattening (real ep2) throw () [inline, static]
Parameters:
[in] ep2 = e' 2 = (a2 - b2) / b2, the second eccentricity squared.
Returns:
f = (a - b) / a, the flattening.
e' 2 should lie in (-1, inf). The returned value f lies in (-inf, 1).
Definition at line 470 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::FlatteningToSecondEccentricitySq (real f) throw () [inline, static]
Parameters:
[in] f = (a - b) / a, the flattening.
Returns:
e' 2 = (a2 - b2) / b2, the second eccentricity squared.
f should lie in (-inf, 1). The returned value e' 2 lies in (-1, inf).
Definition at line 482 of file Ellipsoid.hpp.
References GeographicLib::Math::sq().
static Math::real GeographicLib::Ellipsoid::ThirdEccentricitySqToFlattening (real epp2) throw () [inline, static]
Parameters:
[in] epp2 = e'' 2 = (a2 - b2) / (a2 + b2), the third eccentricity squared.
Returns:
f = (a - b) / a, the flattening.
e'' 2 should lie in (-1, 1). The returned value f lies in (-inf, 1).
Definition at line 494 of file Ellipsoid.hpp.
static Math::real GeographicLib::Ellipsoid::FlatteningToThirdEccentricitySq (real f) throw () [inline, static]
Parameters:
[in] f = (a - b) / a, the flattening.
Returns:
e'' 2 = (a2 - b2) / (a2 + b2), the third eccentricity squared.
f should lie in (-inf, 1). The returned value e'' 2 lies in (-1, 1).
Definition at line 506 of file Ellipsoid.hpp.
References GeographicLib::Math::sq().
Member Data Documentation
const Ellipsoid GeographicLib::Ellipsoid::WGS84 [static]
A global instantiation of Ellipsoid with the parameters for the WGS84 ellipsoid.
Definition at line 515 of file Ellipsoid.hpp.
The documentation for this class was generated from the following files:
Ellipsoid.hpp
Ellipsoid.cpp