GeographicLib: GeographicLib::SphericalEngine::coeff Class Reference
GeographicLib::SphericalEngine::coeff Class Reference
Package up coefficients for SphericalEngine.
#include <GeographicLib/SphericalEngine.hpp>
Public Member Functions
coeff ()
coeff (const std::vector< real > &C, const std::vector< real > &S, int N, int nmx, int mmx)
coeff (const std::vector< real > &C, const std::vector< real > &S, int N)
int N () const throw ()
int nmx () const throw ()
int mmx () const throw ()
int index (int n, int m) const throw ()
Math::real Cv (int k) const
Math::real Sv (int k) const
Math::real Cv (int k, int n, int m, real f) const
Math::real Sv (int k, int n, int m, real f) const
Static Public Member Functions
static int Csize (int N, int M)
static int Ssize (int N, int M)
static void readcoeffs (std::istream &stream, int &N, int &M, std::vector< real > &C, std::vector< real > &S)
Detailed Description
Package up coefficients for SphericalEngine.
This packages up the C, S coefficients and information about how the coefficients are stored into a single structure. This allows a vector of type SphericalEngine::coeff to be passed to SphericalEngine::Value. This class also includes functions to aid indexing into C and S.
The storage layout of the coefficients is documented in SphericalHarmonic and SphericalHarmonic::SphericalHarmonic.
Definition at line 89 of file SphericalEngine.hpp.
Constructor & Destructor Documentation
GeographicLib::SphericalEngine::coeff::coeff () [inline]
A default constructor
Definition at line 98 of file SphericalEngine.hpp.
GeographicLib::SphericalEngine::coeff::coeff (const std::vector< real > & C, const std::vector< real > & S, int N, int nmx, int mmx) [inline]
The general constructor.
Parameters:
[in] C a vector of coefficients for the cosine terms.
[in] S a vector of coefficients for the sine terms.
[in] N the degree giving storage layout for C and S.
[in] nmx the maximum degree to be used.
[in] mmx the maximum order to be used.
This requires N >= nmx >= mmx >= -1. C and S must also be large enough to hold the coefficients. Otherwise an exception is thrown.
Definition at line 117 of file SphericalEngine.hpp.
References GeographicLib::SphericalEngine::RootTable().
GeographicLib::SphericalEngine::coeff::coeff (const std::vector< real > & C, const std::vector< real > & S, int N) [inline]
The constructor for full coefficient vectors.
Parameters:
[in] C a vector of coefficients for the cosine terms.
[in] S a vector of coefficients for the sine terms.
[in] N the maximum degree and order.
This requires N >= -1. C and S must also be large enough to hold the coefficients. Otherwise an exception is thrown.
Definition at line 143 of file SphericalEngine.hpp.
References GeographicLib::SphericalEngine::RootTable().
Member Function Documentation
int GeographicLib::SphericalEngine::coeff::N () const throw () [inline]
Returns:
N the degree giving storage layout for C and S.
Definition at line 162 of file SphericalEngine.hpp.
Referenced by GeographicLib::GravityModel::GravityModel().
int GeographicLib::SphericalEngine::coeff::nmx () const throw () [inline]
Returns:
nmx the maximum degree to be used.
Definition at line 166 of file SphericalEngine.hpp.
Referenced by GeographicLib::SphericalEngine::Circle(), and GeographicLib::GravityModel::GravityModel().
int GeographicLib::SphericalEngine::coeff::mmx () const throw () [inline]
Returns:
mmx the maximum order to be used.
Definition at line 170 of file SphericalEngine.hpp.
Referenced by GeographicLib::SphericalEngine::Circle(), and GeographicLib::GravityModel::GravityModel().
int GeographicLib::SphericalEngine::coeff::index (int n, int m) const throw () [inline]
The one-dimensional index into C and S.
Parameters:
[in] n the degree.
[in] m the order.
Returns:
the one-dimensional index.
Definition at line 178 of file SphericalEngine.hpp.
Math::real GeographicLib::SphericalEngine::coeff::Cv (int k) const [inline]
An element of C.
Parameters:
[in] k the one-dimensional index.
Returns:
the value of the C coefficient.
Definition at line 186 of file SphericalEngine.hpp.
Referenced by GeographicLib::SphericalEngine::Circle().
Math::real GeographicLib::SphericalEngine::coeff::Sv (int k) const [inline]
An element of S.
Parameters:
[in] k the one-dimensional index.
Returns:
the value of the S coefficient.
Definition at line 193 of file SphericalEngine.hpp.
Referenced by GeographicLib::SphericalEngine::Circle().
Math::real GeographicLib::SphericalEngine::coeff::Cv (int k, int n, int m, real f) const [inline]
An element of C with checking.
Parameters:
[in] k the one-dimensional index.
[in] n the requested degree.
[in] m the requested order.
[in] f a multiplier.
Returns:
the value of the C coefficient multiplied by f in n and m are in range else 0.
Definition at line 204 of file SphericalEngine.hpp.
Math::real GeographicLib::SphericalEngine::coeff::Sv (int k, int n, int m, real f) const [inline]
An element of S with checking.
Parameters:
[in] k the one-dimensional index.
[in] n the requested degree.
[in] m the requested order.
[in] f a multiplier.
Returns:
the value of the S coefficient multiplied by f in n and m are in range else 0.
Definition at line 216 of file SphericalEngine.hpp.
static int GeographicLib::SphericalEngine::coeff::Csize (int N, int M) [inline, static]
The size of the coefficient vector for the cosine terms.
Parameters:
[in] N the maximum degree.
[in] M the maximum order.
Returns:
the size of the vector of cosine terms as stored in column major order.
Definition at line 227 of file SphericalEngine.hpp.
static int GeographicLib::SphericalEngine::coeff::Ssize (int N, int M) [inline, static]
The size of the coefficient vector for the sine terms.
Parameters:
[in] N the maximum degree.
[in] M the maximum order.
Returns:
the size of the vector of cosine terms as stored in column major order.
Definition at line 238 of file SphericalEngine.hpp.
void GeographicLib::SphericalEngine::coeff::readcoeffs (std::istream & stream, int & N, int & M, std::vector< real > & C, std::vector< real > & S) [static]
Load coefficients from a binary stream.
Parameters:
[in] stream the input stream.
[out] N The maximum degree of the coefficients.
[out] M The maximum order of the coefficients.
[out] C The vector of cosine coefficients.
[out] S The vector of sine coefficients.
N and M are read as 4-byte ints. C and S are resized to accommodate all the coefficients (with the m = 0 coefficients for S excluded) and the data for these coefficients read as 8-byte doubles. The coefficients are stored in column major order. The bytes in the stream should use little-endian ordering. IEEE floating point is assumed for the coefficients.
Definition at line 382 of file SphericalEngine.cpp.
Referenced by GeographicLib::GravityModel::GravityModel(), and GeographicLib::MagneticModel::MagneticModel().
The documentation for this class was generated from the following files:
SphericalEngine.hpp
SphericalEngine.cpp