GeographicLib: GeographicLib::AzimuthalEquidistant Class Reference
GeographicLib::AzimuthalEquidistant Class Reference
Azimuthal Equidistant Projection.
#include <GeographicLib/AzimuthalEquidistant.hpp>
Public Member Functions
AzimuthalEquidistant (const Geodesic &earth=Geodesic::WGS84) throw ()
void Forward (real lat0, real lon0, real lat, real lon, real &x, real &y, real &azi, real &rk) const throw ()
void Reverse (real lat0, real lon0, real x, real y, real &lat, real &lon, real &azi, real &rk) const throw ()
void Forward (real lat0, real lon0, real lat, real lon, real &x, real &y) const throw ()
void Reverse (real lat0, real lon0, real x, real y, real &lat, real &lon) const throw ()
Inspector functions
Math::real MajorRadius () const throw ()
Math::real InverseFlattening () const throw ()
Detailed Description
Azimuthal Equidistant Projection.
Azimuthal equidistant projection centered at an arbitrary position on the ellipsoid. For a point in projected space (x, y), the geodesic distance from the center position is hypot(x, y) and the azimuth of the geodesic from the center point is atan2(x, y). The Forward and Reverse methods also return the azimuth azi of the geodesic at (x, y) and reciprocal scale rk in the azimuthal direction which, together with the basic properties of the projection, serve to specify completely the local affine transformation between geographic and projected coordinates.
The conversions all take place using a Geodesic object (by default Geodesic::WGS84). For more information on geodesics see Geodesics on the Ellipsoid.
Definition at line 35 of file AzimuthalEquidistant.hpp.
Constructor & Destructor Documentation
GeographicLib::AzimuthalEquidistant::AzimuthalEquidistant (const Geodesic & earth = Geodesic::WGS84) throw () [inline, explicit]
Constructor for AzimuthalEquidistant.
Parameters:
[in] earth the Geodesic object to use for geodesic calculations. By default this uses the WGS84 ellipsoid.
Definition at line 48 of file AzimuthalEquidistant.hpp.
Member Function Documentation
void GeographicLib::AzimuthalEquidistant::Forward (real lat0, real lon0, real lat, real lon, real & x, real & y, real & azi, real & rk) const throw ()
Forward projection, from geographic to azimuthal equidistant.
Parameters:
[in] lat0 latitude of center point of projection (degrees).
[in] lon0 longitude of center point of projection (degrees).
[in] lat latitude of point (degrees).
[in] lon longitude of point (degrees).
[out] x easting of point (meters).
[out] y northing of point (meters).
[out] azi azimuth of geodesic at point (degrees).
[out] rk reciprocal of azimuthal scale at point.
lat0 and lat should be in the range [-90, 90] and lon0 and lon should be in the range [-180, 360]. The scale of the projection is 1 in the "radial" direction, azi clockwise from true north, and is 1/rk in the direction perpendicular to this. A call to Forward followed by a call to Reverse will return the original (lat, lon) (to within roundoff).
Definition at line 24 of file AzimuthalEquidistant.cpp.
Referenced by Forward().
void GeographicLib::AzimuthalEquidistant::Reverse (real lat0, real lon0, real x, real y, real & lat, real & lon, real & azi, real & rk) const throw ()
Reverse projection, from azimuthal equidistant to geographic.
Parameters:
[in] lat0 latitude of center point of projection (degrees).
[in] lon0 longitude of center point of projection (degrees).
[in] x easting of point (meters).
[in] y northing of point (meters).
[out] lat latitude of point (degrees).
[out] lon longitude of point (degrees).
[out] azi azimuth of geodesic at point (degrees).
[out] rk reciprocal of azimuthal scale at point.
lat0 should be in the range [-90, 90] and lon0 should be in the range [-180, 360]. lat will be in the range [-90, 90] and lon will be in the range [-180, 180). The scale of the projection is 1 in the "radial" direction, azi clockwise from true north, and is 1/rk in the direction perpendicular to this. A call to Reverse followed by a call to Forward will return the original (x, y) (to roundoff) only if the geodesic to (x, y) is a shortest path.
Definition at line 35 of file AzimuthalEquidistant.cpp.
Referenced by Reverse().
void GeographicLib::AzimuthalEquidistant::Forward (real lat0, real lon0, real lat, real lon, real & x, real & y) const throw () [inline]
AzimuthalEquidistant::Forward without returning the azimuth and scale.
Definition at line 99 of file AzimuthalEquidistant.hpp.
References Forward().
void GeographicLib::AzimuthalEquidistant::Reverse (real lat0, real lon0, real x, real y, real & lat, real & lon) const throw () [inline]
AzimuthalEquidistant::Reverse without returning the azimuth and scale.
Definition at line 108 of file AzimuthalEquidistant.hpp.
References Reverse().
Math::real GeographicLib::AzimuthalEquidistant::MajorRadius () const throw () [inline]
Returns:
a the equatorial radius of the ellipsoid (meters). This is the value inherited from the Geodesic object used in the constructor.
Definition at line 121 of file AzimuthalEquidistant.hpp.
References GeographicLib::Geodesic::MajorRadius().
Math::real GeographicLib::AzimuthalEquidistant::InverseFlattening () const throw () [inline]
Returns:
r the inverse flattening of the ellipsoid. This is the value inherited from the Geodesic object used in the constructor. A value of 0 is returned for a sphere (infinite inverse flattening).
Definition at line 128 of file AzimuthalEquidistant.hpp.
References GeographicLib::Geodesic::InverseFlattening().
The documentation for this class was generated from the following files:
AzimuthalEquidistant.hpp
AzimuthalEquidistant.cpp