GeographicLib: ConicProj.cpp File Reference
ConicProj.cpp File Reference
Command line utility for conical projections.
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <GeographicLib/LambertConformalConic.hpp>
#include <GeographicLib/AlbersEqualArea.hpp>
#include <GeographicLib/DMS.hpp>
#include "ConicProj.usage"
Functions
int main (int argc, char *argv[])
Detailed Description
Command line utility for conical projections.
Copyright (c) Charles Karney (2009, 2010, 2011) <charles@karney.com> and licensed under the LGPL. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with Geodesic.o GeodesicLine.o AzimuthalEquidistant.o Gnomonic.o CassiniSoldner.o
See the man page for usage information.
Definition in file ConicProj.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file ConicProj.cpp.
References GeographicLib::DMS::Decode(), GeographicLib::DMS::DecodeFraction(), GeographicLib::DMS::DecodeLatLon(), GeographicLib::DMS::Encode(), GeographicLib::DMS::LATITUDE, GeographicLib::DMS::LONGITUDE, and GeographicLib::DMS::NUMBER.