GeographicLib: EquidistantTest.cpp File Reference
EquidistantTest.cpp File Reference
Command line utility for azimuthal equidistant and Cassini-Soldner projections.
#include "GeographicLib/Geodesic.hpp"
#include "GeographicLib/AzimuthalEquidistant.hpp"
#include "GeographicLib/CassiniSoldner.hpp"
#include <iostream>
#include <iomanip>
#include <sstream>
Functions
int usage (int retval)
int main (int argc, char *argv[])
Detailed Description
Command line utility for azimuthal equidistant and Cassini-Soldner projections.
Copyright (c) Charles Karney (2009, 2010) <charles@karney.com> and licensed under the LGPL. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with Geodesic.o AzimuthalEquidistant.o CassiniSoldner.o
See EquidistantTest for usage information.
Definition in file EquidistantTest.cpp.
Function Documentation
int usage (int retval)
Definition at line 23 of file EquidistantTest.cpp.
int main (int argc, char * argv[])
Definition at line 53 of file EquidistantTest.cpp.
References GeographicLib::AzimuthalEquidistant::Forward(), GeographicLib::CassiniSoldner::Forward(), GeographicLib::AzimuthalEquidistant::Reverse(), GeographicLib::CassiniSoldner::Reverse(), usage(), and GeographicLib::Geodesic::WGS84.