GeographicLib: GeodesicProj.cpp File Reference
GeodesicProj.cpp File Reference
Command line utility for geodesic projections.
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <GeographicLib/Geodesic.hpp>
#include <GeographicLib/AzimuthalEquidistant.hpp>
#include <GeographicLib/CassiniSoldner.hpp>
#include <GeographicLib/Gnomonic.hpp>
#include <GeographicLib/DMS.hpp>
#include <GeographicLib/Utility.hpp>
#include "GeodesicProj.usage"
Functions
int main (int argc, char *argv[])
Detailed Description
Command line utility for geodesic projections.
Copyright (c) Charles Karney (2009-2012) charl.nosp@m.es@k.nosp@m.arney.nosp@m..com and licensed under the MIT/X11 License. For more information, see http://geographiclib.sourceforge.net/
Compile and link with g++ -g -O3 -I../include -I../man -o GeodesicProj \ GeodesicProj.cpp \ ../src/AzimuthalEquidistant.cpp \ ../src/CassiniSoldner.cpp \ ../src/DMS.cpp \ ../src/Geodesic.cpp \ ../src/GeodesicLine.cpp \ ../src/Gnomonic.cpp
See the man page for usage information.
Definition in file GeodesicProj.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 37 of file GeodesicProj.cpp.
References GeographicLib::DMS::DecodeLatLon(), GeographicLib::AzimuthalEquidistant::Forward(), GeographicLib::Gnomonic::Forward(), GeographicLib::AzimuthalEquidistant::Reverse(), and GeographicLib::Gnomonic::Reverse().