GeographicLib: Geod.cpp File Reference
Geod.cpp File Reference
Command line utility for geodesic calculations.
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <GeographicLib/Geodesic.hpp>
#include <GeographicLib/GeodesicLine.hpp>
#include <GeographicLib/DMS.hpp>
#include "Geod.usage"
Typedefs
typedef GeographicLib::Math::real real
Functions
std::string LatLonString (real lat, real lon, int prec, bool dms)
std::string AzimuthString (real azi, int prec, bool dms)
std::string DistanceStrings (real s12, real a12, bool full, bool arcmode, int prec, bool dms)
real ReadDistance (const std::string &s, bool arcmode)
int main (int argc, char *argv[])
Detailed Description
Command line utility for geodesic calculations.
Copyright (c) Charles Karney (2009, 2010, 2011) <charles@karney.com> and licensed under the MIT/X11 License. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with Geodesic.o GeodesicLine.o DMS.o
See the man page for usage information.
Definition in file Geod.cpp.
Typedef Documentation
typedef GeographicLib::Math::real real
Definition at line 26 of file Geod.cpp.
Function Documentation
std::string LatLonString (real lat, real lon, int prec, bool dms)
Definition at line 28 of file Geod.cpp.
References GeographicLib::DMS::Encode(), GeographicLib::DMS::LATITUDE, GeographicLib::DMS::LONGITUDE, and GeographicLib::DMS::NUMBER.
Referenced by main().
std::string AzimuthString (real azi, int prec, bool dms)
Definition at line 37 of file Geod.cpp.
References GeographicLib::DMS::AZIMUTH, GeographicLib::DMS::Encode(), and GeographicLib::DMS::NUMBER.
Referenced by main().
std::string DistanceStrings (real s12, real a12, bool full, bool arcmode, int prec, bool dms)
Definition at line 43 of file Geod.cpp.
References GeographicLib::DMS::Encode(), GeographicLib::DMS::NONE, and GeographicLib::DMS::NUMBER.
Referenced by main().
real ReadDistance (const std::string & s, bool arcmode)
Definition at line 57 of file Geod.cpp.
References GeographicLib::DMS::Decode(), and GeographicLib::DMS::DecodeAngle().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 62 of file Geod.cpp.
References GeographicLib::Geodesic::ArcDirect(), AzimuthString(), GeographicLib::DMS::Decode(), GeographicLib::DMS::DecodeAzimuth(), GeographicLib::DMS::DecodeFraction(), GeographicLib::DMS::DecodeLatLon(), GeographicLib::Geodesic::Direct(), DistanceStrings(), GeographicLib::DMS::Encode(), GeographicLib::Geodesic::Inverse(), LatLonString(), GeographicLib::Geodesic::Line(), GeographicLib::DMS::NUMBER, and ReadDistance().