GeographicLib: GeoidEval.cpp File Reference
GeoidEval.cpp File Reference
Command line utility for evaluating geoid heights.
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <GeographicLib/Geoid.hpp>
#include <GeographicLib/DMS.hpp>
#include <GeographicLib/Utility.hpp>
#include <GeographicLib/GeoCoords.hpp>
#include "GeoidEval.usage"
Functions
int main (int argc, char *argv[])
Detailed Description
Command line utility for evaluating geoid heights.
Copyright (c) Charles Karney (2009-2012) <charles@karney.com> and licensed under the MIT/X11 License. For more information, see http://geographiclib.sourceforge.net/
Compile and link with g++ -g -O3 -I../include -I../man -o GeoidEval \ GeoidEval.cpp \ ../src/DMS.cpp \ ../src/GeoCoords.cpp \ ../src/Geoid.cpp \ ../src/MGRS.cpp \ ../src/PolarStereographic.cpp \ ../src/TransverseMercator.cpp \ ../src/UTMUPS.cpp
See the man page for usage information.
Definition in file GeoidEval.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 35 of file GeoidEval.cpp.
References GeographicLib::Geoid::DefaultGeoidName(), GeographicLib::DMS::DecodeLatLon(), GeographicLib::UTMUPS::DecodeZone(), GeographicLib::UTMUPS::MINZONE, GeographicLib::UTMUPS::MAXZONE, GeographicLib::Geoid::DefaultGeoidPath(), GeographicLib::Geoid::CacheAll(), GeographicLib::Geoid::CacheArea(), GeographicLib::Geoid::GeoidFile(), GeographicLib::Geoid::Description(), GeographicLib::Geoid::Interpolation(), GeographicLib::Geoid::DateTime(), GeographicLib::Geoid::Offset(), GeographicLib::Geoid::Scale(), GeographicLib::Geoid::MaxError(), GeographicLib::Geoid::RMSError(), GeographicLib::Geoid::Cache(), GeographicLib::Geoid::CacheSouth(), GeographicLib::Geoid::CacheWest(), GeographicLib::Geoid::CacheNorth(), GeographicLib::Geoid::CacheEast(), GeographicLib::UTMUPS::INVALID, GeographicLib::GeoCoords::Reset(), GeographicLib::GeoCoords::Latitude(), GeographicLib::GeoCoords::Longitude(), and GeographicLib::Math::isnan().