GeographicLib: MagneticField.cpp File Reference
MagneticField.cpp File Reference
Command line utility for evaluating magnetic fields.
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <ctime>
#include <GeographicLib/MagneticModel.hpp>
#include <GeographicLib/DMS.hpp>
#include <GeographicLib/Utility.hpp>
#include "MagneticField.usage"
Functions
int main (int argc, char *argv[])
Detailed Description
Command line utility for evaluating magnetic fields.
Copyright (c) Charles Karney (2011) <charles@karney.com> and licensed under the MIT/X11 License. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with MagneticModel.o DMS.o SphericalEngine.o
See the man page for usage information.
Definition in file MagneticField.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 27 of file MagneticField.cpp.
References GeographicLib::MagneticModel::DateTime(), GeographicLib::DMS::DecodeLatLon(), GeographicLib::MagneticModel::DefaultMagneticName(), GeographicLib::MagneticModel::DefaultMagneticPath(), GeographicLib::MagneticModel::Description(), GeographicLib::DMS::Encode(), GeographicLib::MagneticModel::FieldComponents(), GeographicLib::MagneticModel::MagneticFile(), GeographicLib::MagneticModel::MagneticModelName(), GeographicLib::MagneticModel::MaxHeight(), GeographicLib::MagneticModel::MaxTime(), GeographicLib::MagneticModel::MinHeight(), GeographicLib::MagneticModel::MinTime(), GeographicLib::DMS::NUMBER, and GeographicLib::Utility::str().