GeographicLib: Planimeter.cpp File Reference
Planimeter.cpp File Reference
Command line utility for measuring the area of geodesic polygons.
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <GeographicLib/PolygonArea.hpp>
#include <GeographicLib/DMS.hpp>
#include <GeographicLib/GeoCoords.hpp>
#include "Planimeter.usage"
Functions
int main (int argc, char *argv[])
Detailed Description
Command line utility for measuring the area of geodesic polygons.
Copyright (c) Charles Karney (2010, 2011) <charles@karney.com> and licensed under the MIT/X11 License. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with Geodesic.o GeodesicLine.o DMS.o
See the man page for usage information.
Definition in file Planimeter.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 25 of file Planimeter.cpp.
References GeographicLib::PolygonArea::AddPoint(), GeographicLib::PolygonArea::Clear(), GeographicLib::PolygonArea::Compute(), GeographicLib::DMS::Decode(), GeographicLib::DMS::DecodeFraction(), GeographicLib::DMS::Encode(), GeographicLib::Math::isnan(), GeographicLib::DMS::NUMBER, and GeographicLib::GeoCoords::Reset().