GeographicLib: TransverseMercatorProj.cpp File Reference
TransverseMercatorProj.cpp File Reference
Command line utility for testing transverse Mercator projections.
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <GeographicLib/EllipticFunction.hpp>
#include <GeographicLib/TransverseMercatorExact.hpp>
#include <GeographicLib/TransverseMercator.hpp>
#include <GeographicLib/DMS.hpp>
#include "TransverseMercatorProj.usage"
Functions
int main (int argc, char *argv[])
Detailed Description
Command line utility for testing transverse Mercator projections.
Copyright (c) Charles Karney (2008, 2009, 2010, 2011) <charles@karney.com> and licensed under the LGPL. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with TransverseMercatorExact.o EllipticFunction.o TransverseMercator.o
See the man page for usage information.
Definition in file TransverseMercatorProj.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 28 of file TransverseMercatorProj.cpp.
References GeographicLib::DMS::Decode(), GeographicLib::DMS::DecodeLatLon(), GeographicLib::DMS::Encode(), GeographicLib::DMS::LATITUDE, and GeographicLib::DMS::NUMBER.