=for comment $Id$

=head1 NAME

GeoConvert(1) -- convert geographic coordinates

=head1 SYNOPSIS

`GeoConvert` [`-g`|`-d`|`-u`|`-m`|`-c`] [`-p` <prec>]
[`-z` <zone>|`-s`|`-t`] [`-n`] [`-h`]

## DESCRIPTION

`GeoConvert` reads from standard input interpreting each line as a
geographic coordinate and prints the coordinate in the format specified
by the options on standard output.  The input is interpreted in one of
three different ways depending on how many space or comma delimited
tokens there are on the line.  The options `-g`, `-d`, `-u`, and `-m`
govern the format of output.  In all cases, the WGS84 model of the earth
is used.

* `geographic` (2 tokens, output options `-g` or `-d`):
  given as <latitude> <longitude> using decimal degrees or degrees
  minutes seconds.  d, ', and " are used to denote degrees, minutes, and
  seconds, with the least significant designator optional.  Latitude is
  given first;  however, on input, either may be given first by
  appending or prepending _N_ or _S_ to the latitude and _E_ or _W_ to
  the longitude.  For example, the following are all equivalent
      33.3 44.4
      E44.4 N33.3
      33d18'N 44d24'E
      44d24 33d18N
* `UTM/UPS` (3 tokens, output option `-u`):
  given as <zone>+<hemisphere> <easting> <northing> or <easting>
  <northing> <zone>+<hemisphere>, where <hemisphere> is either _N_ or
  _S_.  The <zone> is absent for a UPS specification.  For example,
      38N 444140.54 3684706.36
      444140.54 3684706.36 38N
      S 2173854.98 2985980.58
      2173854.98 2985980.58 S
* `MRGS` (1 token, output option `-m`):
  is used to specify the center of an MGRS grid square.  For example,
      38SMB4484
      38SMB44140847064

## OPTIONS

* `-g`:
  output latitude and longitude (decimal degrees).  Default output mode.
* `-d`:
  output latitude and longitude (DMS, degrees minutes seconds).
* `-u`:
  output UTM or UPS.
* `-m`:
  output MGRS.
* `-c`:
  output meridian convergence and scale for the corresponding UTM or
  UPS projection.  Convergence is the bearing of grid north given as
  degrees clockwise from true north.
* `-p` <prec>:
  set the precision relative to 1m; see [PRECISION][].  (default <prec> = 0.)
* `-z` <zone>:
  set the zone for output.  Use either a positive number for a UTM zone
  or <zone> = 0 to specify UPS.  Alternatively use a <zone>+<hemisphere>
  designation (<hemisphere> is ignored), e.g., 38N.  See [ZONE][].
* `-s`:
  use the standard UPS and UTM zones.
* `-t`:
  similar to `-s` but forces UPS regions to the closest UTM zone.
* `-n`:
  on input, MGRS coordinates refer to the south-west corner of the MGRS
  square instead of the center; see [MGRS][].
* `-h`, `--help`:
  print help.

## PRECISION

<prec> gives precision of the output with <prec> = 0 giving 1m
precision, <prec> = 3 giving 1mm precision, etc.  <prec> is the number
of digits after the decimal point for UTM/UPS.  The number of digits per
coordinate for MGRS is 5 + <prec>.  For decimal degrees, the number of
digits after the decimal point is 5 + <prec>.  For DMS (degree, minute,
seconds) output, the number of digits after the decimal point in the
seconds components is 1 + <prec>; if this is negative then use minutes
(<prec> = -2 or -3) or degrees (<prec> &le; -4) as the least significant
component.  Print convergence, resp. scale, with 5 + <prec>, resp. 7 +
<prec>, digits after the decimal point.  The minimum value of <prec> is
-5 and the maximum is 9 for UTM/UPS, 9 for decimal degrees, 10 for DMS,
6 for MGRS, and 8 for convergence and scale.

## MGRS

MGRS coordinates represent a square patch of the earth, thus 38SMB4488
is in zone 38N with 444km &le; <easting> &lt; 445km and 3688km &le;
<northing> &lt; 3689km.  Consistent with this representation,
coordinates are _truncated_ (instead of _rounded_) to the requested
precision.  Similiarly, on input an MGRS coordinate represents the
_center_ of the square (38N 444500 3688500 in the example above).
However, if the `-n` option is given then the south-west corner of the
square is returned instead (38N 444000 3688000 in the example above).

## ZONE

If the input is `geographic`, `GeoConvert` uses the standard rules of
selecting UTM vs UPS and for assigning the UTM zone (with the Norway and
Svalbard exceptions).  If the input is `UTM/UPS`, or `MGRS`, then the
choice beteen UTM and UPS and the UTM zone mirrors the input.  The `-z`
<zone>, `-s`, `-t` options allow these rules to be overridden with
<zone> = 0 being used to indicate UPS.  For example, the point
    79.9S 6.1E
corresponds to possible MGRS coordinates
    32CMS4324728161 (standard UTM zone = 32)
    31CEM6066227959 (neighboring UTM zone = 31)
      BBZ1945517770 (neighboring UPS zone)
then
    echo 79.9S 6.1E      | GeoConvert -p -3 -m       ==> 32CMS4328
    echo 31CEM6066227959 | GeoConvert -p -3 -m       ==> 31CEM6027
    echo 31CEM6066227959 | GeoConvert -p -3 -m -s    ==> 32CMS4328
    echo 31CEM6066227959 | GeoConvert -p -3 -m -z 0  ==>   BBZ1917

## EXAMPLES

    echo 38SMB4488 | GeoConvert          ==> 33.33424 44.40363
    echo 38SMB4488 | GeoConvert -d -p 1  ==> 33d20'03.25"N 044d24'13.06"E
    echo 38SMB4488 | GeoConvert -u       ==> 38N 444500 3688500
    echo E44d24 N33d20 | GeoConvert -m -p -3 ==> 38SMB4488

## ERRORS

An illegal line of input will print an error message beginning with
_ERROR:_ and causes `GeoConvert` to return an exit code of 1.  However,
an error does not cause `GeoConvert` to terminate; following lines will
be converted.

## ABBREVIATIONS

* `UTM`:
  [Universal Transverse Mercator](http://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system).
* `UPS`:
  [Univeral Polar Stereographic](http://en.wikipedia.org/wiki/Universal_Polar_Stereographic).
* `MGRS`:
  [Military Grid Reference System](http://en.wikipedia.org/wiki/Military_grid_reference_system).
* `WGS84`:
  [World Geodetic System 1984](http://en.wikipedia.org/wiki/WGS84).

## SEE ALSO

`GeoConvert` is a part of [GeographicLib](http://geographiclib.sf.net).
