=for comment $Id$

=head1 NAME

Planimeter(1) -- compute the area of geodesic polygons

=head1 SYNOPSIS

Usage: Planimeter [-s] [-r] [-e a r] [-h]
$Id$

Measure the area of a geodesic polygon.  Reads polygon vertices from
standard input, one per line.  Vertices may be given as latitude and
longitude, UTM/UPS, or MGRS coordinates (interpreted in the same way as
GeoConvert).  (MGRS coordinates signify the center of the corresponing
MGRS square.)  The end of input, a blank line, or a line which can't be
interpreted as a vertex signals the end of one polygon and the start of
the next.  For each polygon print a summary line with the number of
points, the perimeter (in meters), and the area (in meters^2).

By default, areas are traversed in a counter-clockwise sense (in other
words, the included area is to the left of the perimeter) and a
positive area is returned.  By this rule, a polygon tranversed in a
clockwise sense will return the area of ellipsoid excluded by the
polygon; however, if the -s option is given, the signed area will be
returned.  If the -r option is given, the included area is to the right
of the perimeter.  The -s and -r flags are toggles; repeating one of
then reverses the previous setting.  Only simple polygons are supported
for the area computation.  Polygons may include one or both poles.

By default, the WGS84 ellipsoid is used.  Specifying "-e a r" sets the
equatorial radius of the ellipsoid to "a" and the reciprocal flattening
to r.  Setting r = 0 results in a sphere.  Specify r < 0 for a prolate
ellipsoid.

-h prints this help.

=head1 SEE ALSO

B<Planimeter> is a part of GeographicLib,
L<http://geographiclib.sf.net>.
